### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by toonjoey** [toonjoey/Toonjoey-Site#1]
Discuss my new stuff here.

**Comment by rocketprogrammer** [comment]
add toontown 1997 otp sever

**Comment by rocketprogrammer** [comment]
inb4 wont fix tag

**Comment by toonjoey** [comment]
sure ill put that next to the dp rom link

**Comment by rocketprogrammer** [comment]
aw really

**Comment by rocketprogrammer** [comment]
bruh

**Comment by toonjoey** [comment]
oh and also next to the fuzzy pumper palette shop source code link
